apiVersion: v1
kind: Service
metadata:
  labels:
    app: istio-pilot
  name: istio-pilot
  namespace: istio-system
spec:
  ports:
  - name: grpc-xds
    port: 15010
    protocol: TCP
    targetPort: 15010
  - name: https-xds
    port: 15011
    protocol: TCP
    targetPort: 15011
  - name: http-legacy-discovery
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: http-monitoring
    port: 15014
    protocol: TCP
    targetPort: 15014
---
kind: Endpoints
apiVersion: v1
metadata:
  name: istio-pilot
  namespace: istio-system
subsets:
  - addresses:
      - ip: 172.23.161.98
    ports:
    - name: grpc-xds
      port: 15010
      protocol: TCP
    - name: https-xds
      port: 15011
      protocol: TCP
    - name: http-legacy-discovery
      port: 8080
      protocol: TCP
    - name: http-monitoring
      port: 15014
      protocol: TCP

